### PR TITLE
Add ReadOnlyAPI option in IBController.ini

### PR DESCRIPTION
**Pull request by jacktang**
The commit could disable Read-Only API mode

### CODE REVIEW

**Comment by rlktradewright** [comment]
IBController is not intended to be a TWS/Gateway configuration mechanism. 

It is also my policy not to include code that is only relevant when using the demo system, which is the case here (for live and paper accounts, you just need to disable read-only API once, and TWS/Gateway will remember the setting for ever more).

**Comment by jaredbroad** [comment]
Thanks @jacktang, I'll pull your fork for [QuantConnect/Lean](https://github.com/QuantConnect/Lean).

Please consider this feature @rlktradewright - allowing key API settings to be configured would make IBController more usable out of the box and encourage its adoption.

**Comment by rlktradewright** [comment]
@jaredbroad Well actually I've been considering this feature more or less continually ever since IB introduced this rather silly default setting in autumn 2015. As it happens I'm just in the process of writing something on this topic, which I hope to send out tomorrow, but I'll just quickly explain here why I've taken this stance so far.

The issue here is that I'm concerned that providing the means to clear the ReadOnly API setting will just be the thin end of the wedge. In order to get your TWS/Gateway properly set up for live trading, there are many settings that need to be considered, not just the API settings. In particular you need to make sure that the Presets for the various security types are appropriately set for your trading strategies and risk management. It may be that you don't care about them because your trading platform has its own risk management and defaults built into it, and in this case you can override the presets (in the Precautions section). Now, I have absolutely no intention of providing the ability to set all of those via IBController: it would be a big task, very error prone to configure, and almost certainly quite fragile and subject to breaking when IB introduce new options/

It makes a lot more sense to me to configure your TWS or Gateway exactly the way you want it in an environment where you can use the TWS and Gateway GUIs, and then simply copy the entire configuration over to your target machine. It's so simple to do, and avoids polluting IBController with vast amounts of code that needs to be supported and maintained, and that gets executed every time you start TWS/Gateway only to find that everything is already configured correctly. Also the TWS/Gateway configuration pages are probably the most likely areas to introduce changes that break IBController.

But more tomorrow...

**Comment by jaredbroad** [comment]
@rlktradewright - thank you for reply, I definitely appreciate how much work it would be to maintain backwards compatibility with previous versions of IB. Given how well you tag your releases maybe its feasible to drop backwards compatibility and pin IBController releases to a certain IB version?

I appreciate your suggestion to copy the settings directory, I got this working with 1 person -- but the next live account which used the platform ran into the same issue. Asking _every_ user of a product to repeat the same process is a tedious barrier to usage. 

I got it working for the second person by copying _my_ settings files across to their account folder. But without being able to guess the folder name dxxxx in advance it will be impossible to do without first failing (I think?).

For now I've built & tested this PR and got it to work with any login credentials.

**Comment by rlktradewright** [comment]
Backward compatibility has never really been much of a problem. 

Problems arise because IBController is totally dependent on the structure of the various TWS/Gateway dialogs it interacts with. Whenever IB changes a dialog that IBController has an interest in, there is the potential for this to break IBController. Buttons, checkboxes, and radio buttons are the easiest to deal with because they can be programmatically located using their labels (but a change to a label will break IBController). Text boxes are more difficult because they don't have any identifiers that IBController can use to find them, so it has to locate them by position, eg 'get me the 4th text box in this dialog': so if IB add a new text box such that what was the 4th one now becomes the 5th one, that will also break IBController. Similarly there are changes IB can make to a dialog that prevent IBController from recognising it at all.

So whenever this sort of breaking change happens, IBController has to be fixed to deal with it. This is a matter of analysing the dialog structure information generated by the .ini file setting `LogComponents=open`, working out what has changed, and making the appropriate adjustments to the code. Usually its pretty straightforward to do this, but sometimes it can take a while to get it right.

Now provided I notice such a change before people start trying to use IBController with that version of TWS/Gateway, and I get it fixed reasonably promptly, I can usually avoid too many complaints: and since most people use the stable TWS versions rather than the latest versions with IBController, I don't usually feel too much pressure to make the changes, but of course I must do it before the offending version is declared to now be the stable one.

So it's really quite important to me to minimise the opportunities for such breakages, and that's why I've always taken the view that IBController is NOT a mechanism for configuring TWS/Gateway, which have perfectly good configuration facilities built into them. 

However, recently there seems to be an increasing interest in running headless and/or on remote machines, in containers, etc. Now I have no problem with this, and I've been encouraging people to accomplish this by doing their TWS/Gateway configuration on a local machine with visibility of the GUI, because that's the easiest way of making sure it all works properly, and then simply copying their configuration over to the target machine. Provided you copy the right stuff over (and it seems more guidance about this needs to be provided) this works fine and is very straightforward. In fact this afternoon I copied my paper trading gateway setup from my main Windows server over to a Ubuntu virtual machine, and it all just worked with no difficulty (I didn't copy the TWS jar files because I thought they might not work, but in fact they really ought to and I will try this when I get time).

Ok, now let's try and get this all into perspective. You have your live Gateway and your trading application running nicely on TWS 949 (say) on a headless Linux server. IB release a new version of TWS, version 952, and eventually they declare this to be the current stable version, so you decide you'd better think about upgrading. So do you just install 952 on your live system, and start running your live application against it? No of course not, you want to test it first. I imagine you do something like this:

1. Of course you've already read the Release Notes which tell you there's a new Read-Only API setting. So probably the first thing you do is install 952 on a local machine (not headless), then start it using the IB-provided shortcuts and log in to the demo account, just to see what it looks like and make sure it basically works.

2. Then you set up IBController to run it locally, logging into your paper trading account, with a local copy of your trading application to make sure that also still basically works. Because it's local you have no problem setting the API configuration: note however that you can't do any realistic testing because your live TWS/Gateway is elsewhere and you won't be able to get any market data. 

3. So then you install 952 on your headless server (alongside your live 949) and copy your paper trading configuration over to it, and run that for a few days, checking that it gives the same sort of results as your live system (it probably won't be identical because you can't guarantee that IB's paper trading 'exchange' will give you the same fills as the real exchange).

4. When you're convinced that the new version is acceptable, and you want to put your live system onto 952, you wait for the weekend and do the same as you did for the paper system but this time with your live account username and password, and make sure that the system comes up properly logged in etc, then copy that over to the live system.

Now how hard was that? Every step is easy, and you can be damn sure that what you've got on your remote headless server will work correctly. And having done it, you don't have to touch it again until IB declares the next stable release, or indeed until you have some reason to want to change it (for example, I only updated the live TWS on my server from 944 to 952 in March this year - 944 was at least 2 years old then and was still working perfectly for my needs). 

As far as the scenario above is concerned, there's absolutely no need for IBController to be able to unset the Read-Only API option, because that gets done locally using the configuration dialog.

So why so much demand for this ability in IBController? As far as I can see, it's because people insist on using IBController to load the demo system, which of course resets the API options back to their default state every time you log in. I have absolutely no sympathy with this: I see no reason at all to want to use the API in any significant way with the demo system, other than perhaps for the very earliest stages of order handling code development, and for this purpose there's no point in doing it on anything other than a local computer, using TWS rather than the gateway so that you can see directly whether your orders are working properly. 

Anyone thinking they can develop any kind of serious trading system using only the demo system is kidding themselves, so they need a paper trading system, which means a funded account.

@jaredbroad I'd just like to directly address a couple of your points. First, it's worthwhile using the `IbDir=` setting in IBController to have different TWS settings directories for live, paper and demo accounts (therefore you need separate IBConroller.ini files for each).This makes it much easier to copy your configuration over to your target server, because you literally just copy the relevant settings directory and all its contents: you don't have to know which dxxx directory relates to live or paper accounts. 

Second, you say '_Asking every user of a product to repeat the same process is a tedious barrier to usage_', but I think this is a bit strong. It's only those who insist on running headless that have to do this at all, and having done it correctly once, they'll never look back (especially if they write a script). Also people need to take a serious approach to deploying their live system, the same as any other live IT system: mistakes made doing this can be costly!

Frankly I don't understand why anyone would want to run headless while they're setting up their system anyway: why not have a GUI capability (for example using xvfb and VNC) until you know everything is working fine, then disable the VNC when you really don't want to be able to interact with TWS/Gateway any more?

**Comment by jaredbroad** [comment]
Thank you for the detailed reply. Sorry I forgot to give pretext to the comment -- on [QuantConnect](https://www.quantconnect.com) we allow cloning and trading a live algorithm on a dedicated 512Mb headless linux server with a html5 beautiful GUI/charts in about 60 seconds :) [video](https://www.youtube.com/watch?v=TSHLeSPMcUo). We handle all those deployment steps/issues for them, its an open source community of thousands of people. I'm hoping I can solve it for them with the ReadOnlyAPI setting rather than asking them all to upload settings files.

You are right that it is my particular application, and I definitely understand why it might look like an iceberg feature :) My humble 2c is that being able to _use_ the API is the only setting that is absolutely required.

**Comment by bfreis** [comment]
@rlktradewright, @jaredbroad - just wanted to add 2c on this.

I have almost the exact same issue as Jared mentioned, but for my personal stuff. I'm building my own multi-broker automated trading system using a combination of AWS services, including AWS Lambda and EC2 Container Service. ECS is used to launch a docker container which runs IBController and IB Gateway. I would love to have IBController disable ReadOnlyAPI not for demo, but to trade my own account!

These docker containers with IBController + IB Gateway are destroyed and recreated (as well as rebuilt from scratch) quite frequently, as part of my trading CI/CD...

**Comment by rlktradewright** [comment]
@jaredbroad and @bfreis 

Thanks very much for this additional input. It gives me much more insight into where you're coming from, and the particular problems you're trying to solve.

I've been sticking hard on the issue of Read-only API because as I indicated earlier I think it's just the tip of an iceberg. For example, no-one seems to be concerned about the fact that out-of-the-box, the Precautions settings in the API configuration are all unset. This means that all the pre-defined presets apply. So what happens, Jared, if one of your users tries to place an order for 10 ES contracts, or that risks more than 3% of the account (or whatever the default settings are)? Answer: it will fail. Is this a problem for you? Only you can answer that, but you absolutely must consider these things if you're offering a public service.

So it seems to me that this whole issue is not so much about Read-only API as about "how do I completely configure my TWS/Gateway to meet the user's requirements". At the moment I don't have an answer to that question for the general cases that you're facing, and I don't particularly see it as my problem: I'm just fairly certain that dynamic configuration using IBController is not the right solution. Of course it could be done that way: but it doesn't 'feel' right to me and I don't currently want that code to be part of the official IBController base until I'm convinced that there is no better way.

So someone needs to do some creative thinking about other ways to address this bigger issue. I think the key to this must be the xml configuration file ibg.xml: the API settings are all under the <ApiSettings> tag, and the fact that it's XML means it's easy to manipulate programmatically if necessary. As far as I can tell, it doesn't even contain the account number, so it should be easy to set up, just once, a generic ibg.xml that contains all the configuration needed for your specific uses, and just copy it into place every time you provision a server after installing TWS/Gateway.

There are other options of course. You're perfectly entitled to make any modifications you like to the IBController code for your own use, and you can offer them back for inclusion in the base and I'll 
assess them accordingly.

Another possibility is to introduce the plugin architecture outlined in Issue #44. This would make it relatively easy to introduce this sort of 'marginal' functionality in a way that can be used by others without needing any modification to the 'official' IBController code. However it would be a considerable effort to develop it, and interesting though it would be, I don't have time for it.

Yet another possibility is one I've already mentioned privately to you, Jared, which is for someone else to take over IBController. I simply cannot continue to spend so much time on it, especially when I'm personally perfectly happy with it as it is. If it's out of my hands, I don't really care what happens to it (as long as it remains 'free'). Given that you're running a commercial operation using IBController (or a fork from it), it would seem to be in your interests to find someone that can do this: you claim to be recruiting on your QuantConnect website, so why not make sure one of your recruits has the capability to do this as part of their job, if you don't already have someone?

**Comment by bfreis** [comment]
@rlktradewright -

Thanks for all your responses. Your reasoning makes total sense - the read only api setting would definitely be just the tip of the iceberg. I haven't thought about the issue with the precaution settings before you mentioned it (for my own, personal system, I want them gone as my code will manage position sizes and risks, etc).

I thought of another solution that will most likely solve my own problem, maybe it could help other people following this thread, so here it goes. I'm going to have a VNC server running inside this docker container so I can connect to it and configure IB Gateway (better than configuring locally as I've configured my whole environment to automatically reconnect to IB if anything happens to the IB Gateway, including if I "hijack" my own session by connecting from my laptop -- so I would have to disable all this, just so I could connect from my laptop to generate the ibg.xml file, etc).

So, I will VNC into the headless docker container running IB Gateway + IB Controller, change the settings, and configure the container to sync any changes to the files inside the Jts/dxxxxx/ folder to a bucket in Amazon S3, and also have the docker container retrieve everything from this Amazon S3 bucket back into the Jts folder when a new container launches.

This should probably solve my problem!

Thanks for the inspiration! :)

Cheers

**Comment by rlktradewright** [comment]
I just want to add a couple of observations here about the content of this PR. They may be instructive for future PR contributors.

First, the default for `ForceTwsApiPort` has been changed from nothing (ie don't do anything with this setting) to 4001. This immediately means that every IBController.ini file in existence probably needs to be changed, because the vast majority of them probably don't want the API port number to be 4001: they just want to use the value they've already configured. That's why this setting is called `ForceTwsApiPort`, because you only use it when you want to force it to something other than whatever your TWS settings files have recorded as its value. (Actually, re-reading it now I think the comment associated with this setting needs to be improved to clarify that nearly all users won't need to set it.)

The general rule when modifying IBController is that no change should force users to update their .ini file unless it's unavoidable or they need to take advantage of some new feature for which the default is not suitable.

Secondly, the default setting for the proposed `ReadOnlyAPI` setting should be 'don't change from current setting' rather than 'no'. By now, many TWS users should be using TWS 952 or later, and have therefore already manually configured their TWS or Gateway to turn off this silly default that IB introduced. They will almost certainly never want to change this setting again, so they don't need IBController to do anything on their behalf. 

Thirdly, the removal of the condition in what was line 549 (now 551) of IBController.java means that IBController will open the API configuration dialog every time it starts, even if there is nothing to be set in it (which for nearly all users will be the case). This isn't a big deal, but why force this to happen unnecessarily? I hardly need add that the condition needs to be extended to check whether or not the `ReadOnlyAPI` setting is defaulted.

**Comment by DxCx** [comment]
Thanks for the PR @jacktang. :+1: 
I was just about to implement this myself then i've found your PR. :)
going to merge your branch into mine.

@rlktradewright  - thanks for your comments,
I've Changed the default behavior to true (Safety first ;))

**Pull request closed without merging**
