### PR TITLE
New Read-Only API option

### PR DESCRIPTION
**Pull request by nbauma109**
As suggested in the "Read-Only API" issue, I'm submitting this pull request with a 3-state option (yes/no/blank) called ReadOnlyAPI to keep control of this setting that seems to be changed unexpectedly and repeatedly by TWS.

### CODE REVIEW

**Comment by rlktradewright** [comment]
I expressed my reservations about including this option in issue #31. I still have those reservations, but the bad behaviour of TWS 9.53 regarding the Read-only API setting perhaps adds weight to your argument.

However, I'm no keener on IBController being used to provide workarounds for IB bugs than I am on it providing a backstop for user misconfiguration.

So at the moment, I'd prefer to put a bit more effort into being able to reliably reproduce IB's bug so that we can report it to them. If this turns out not to be possible, I'll report the bug anyway, but I'm not confident they'll take much notice if we can't give them hard evidence. In that case, your enhancement would be worth including.

**Comment by nbauma109** [comment]
I'm confused, what unhandled exception would be thrown ?
The findCheckBox does not throw an exception when the checkbox is not found, but it returns null, and there is a null check to handle that. 
I removed the "throw IBControllerException" on purpose for older versions that do not have the Read-Only API checkbox. Am I missing something here ?

**Comment by rlktradewright** [comment]
Apologies, I misread your code due to the formatting of your if statement. The statements beginning 
`if ("yes".equals(...` 
and 
`if ("no".equals(...` 
need to be indented an extra level.

Regarding throwing the exception if cb == null, the idea here is that if someone has set `ReadOnlyAPI=yes` but they're actually using an older TWS version, then at least something is logged to indicate why they're not getting a read-only API. There's also always the possibility that IB might do something in a later TWS version that stops it working properly, such as renaming the checkbox or redesigning the configuration dialog. I've always been torn between two approaches to this sort of thing:
* EITHER abort the process (because it's either misconfigured or changed in some way, and therefore potentially harmful)
* OR log some information and carry on so that if the user notices something is amiss at least there's something in the log that might be helpful. 

In fact in this case it's arguable that if `ReadOnlyAPI=yes`, and we can't be sure that this setting is actually correctly set in TWS, then we should abort the process anyway because of the potential security implications. Anyway this sort of detail can be resolved when/if we finally accept the pull request.

**Comment by nbauma109** [comment]
I updated the pull request to keep a single task that is not executed if neither of TWS API port and Read-Only API are set. Also, if a value is set for ReadOnly but the checkbox is not found, I chose to abort the process.

**Comment by SKoschnicke** [comment]
I would like to add that I also see this as a valid feature for IBController because the default setting is read-only, making it impossible to start Gateway for usage with an API client in an unsupervised manner, as I laid out in my PR #63 (I wish I had seen this PR earlier, because I also added this exact same feature :) )

**Comment by rlktradewright** [comment]
Since the pros and cons related to this subject were exhaustively discussed in PR #63, I'll now close this.

**Pull request closed without merging**
