### PR TITLE
rm blank line from INI settings table

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by rlktradewright** [comment]
Not sure I agree with you. I think the table looks better with a terminating line, rather than the last entry just hanging.

However this table is inconsistent with the earlier one, so I need to fix one of them!

**Comment by dandv** [comment]
Yes, the first table uses the [correct Markdown formatting for tables](https://help.github.com/articles/organizing-information-with-tables/) :)

**Comment by rlktradewright** [comment]
It may not be correct Github-flavoured Markdown, but it's correct within the Markdown editor I use to generate the PDF (stackedit.io), and it strikes me as being an entirely reasonable construct that shouldn't cause too much trouble for those who prefer to read raw markdown.

What I care about is the end result, ie the PDF. Markdown is only a convenient means to an end as far as I'm concerned.

The examples in the link you gave show the table rendering with a terminating line, which is how I think it should be. Trouble is, stackedit.io doesn't do that. Is that a bug? Perhaps, but putting in the extra line gives me what I want, and I don't think it's going to cause too much trouble for those who prefer to read raw markdown.

Interestingly I notice that GitHub renders a table with the extra line in a very silly way: I would say that _is _ a bug, because the intent is surely clear (but I suppose it caters for the common case where the author does actually want to fill a table row with hyphens!): 

| Header1            | Header2                                                         |
| ------------------ | ------------------------------------------------------------- |
| Wizzly          | Wazzox                         |
| Crumbly  | Werbles|
| ------------------ | ------------------------------------------------------------- |

Anyway I've discovered that stackedit.io also gives me what I want if I simply add an extra row of blank cells. This may look more comfortable in other markdown viewers. So that's what I'll do.

**Comment by dandv** [comment]
Any updates? Related: #114.

**Comment by rlktradewright** [comment]
I updated the userguide.md on April 4 2017, in the way I indicated above.

I haven't regenerated the PDF yet, as I still have some updates to do to it.

I'm well aware that I've neglected IBController recently, but there are only so many hours in a day and I have other (much) higher priorities.

However be assured that if someone actually has a problem with IBController, as opposed to a concern over 'incorrect' markdown, that does get my attention.

**Pull request closed without merging**
